default_agent: main
agents:
  main:
    name: main
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::145023138732:role/agentcore-main-role
      account: '145023138732'
      region: us-west-2
      ecr_repository: 145023138732.dkr.ecr.us-west-2.amazonaws.com/bedrock_agentcore-main
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: 7993c527-d45a-4d99-876a-b18e134466d9
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-3f17cd82
