default_agent: dev
agents:
  dev:
    name: dev
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::145023138732:role/agentcore-dev-iam-role
      execution_role_auto_create: true
      account: '145023138732'
      region: us-east-1
      ecr_repository: 145023138732.dkr.ecr.us-east-1.amazonaws.com/bedrock_agentcore-dev
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: dev-7IRV2WDSok
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:145023138732:runtime/dev-7IRV2WDSok
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
