default_agent: main
agents:
  main:
    name: main
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::145023138732:role/agentcore-main-role
      account: '145023138732'
      region: eu-central-1
      ecr_repository: 145023138732.dkr.ecr.us-west-2.amazonaws.com/bedrock_agentcore-main
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: main-4mv1tO32lm
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:145023138732:runtime/main-4mv1tO32lm
      agent_session_id: 7993c527-d45a-4d99-876a-b18e134466d9
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-27fae46b
