default_agent: main
agents:
  main:
    name: main
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::145023138732:role/agentcore-main-role
      execution_role_auto_create: false
      account: '145023138732'
      region: us-east-1
      ecr_repository: 145023138732.dkr.ecr.us-east-1.amazonaws.com/bedrock_agentcore-main
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: main-C8ZCR3BtkJ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:145023138732:runtime/main-C8ZCR3BtkJ
      agent_session_id: 5af39077-3e8d-4398-9fca-b6000118b3e9
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-0e6b8599
