default_agent: src_mortgage_processor_main
agents:
  src_mortgage_processor_main:
    name: src_mortgage_processor_main
    entrypoint: ./src/mortgage_processor/main.py
    platform: linux/arm64
    container_runtime: docker
    source_path: ./
    aws:
      execution_role: arn:aws:iam::145023138732:role/agentcore-dev-iam-role
      execution_role_auto_create: true
      account: '145023138732'
      region: us-east-1
      ecr_repository: 145023138732.dkr.ecr.us-east-1.amazonaws.com/bedrock_agentcore-dev
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: src_mortgage_processor_main-SSl11IF66g
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:145023138732:runtime/src_mortgage_processor_main-SSl11IF66g
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: src_mortgage_processor_main_mem-BjQ1lAH0Z5
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:145023138732:memory/src_mortgage_processor_main_mem-BjQ1lAH0Z5
      memory_name: src_mortgage_processor_main_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
