[project]
name = "mortgage-processor"
version = "0.1.0"
description = "Mortgage processing application"
requires-python = ">=3.13"
dependencies = [
    "fastmcp",
    "pydantic",
    "boto3",
    "httpx",
    "strands-agents",
    "strands-agents-tools",
    "bedrock-agentcore",
    "aws-opentelemetry-distro",
    "bedrock-agentcore-starter-toolkit",
    "uv",
    "requests",
    "pyyaml",
    "pynamodb"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"